apiVersion: v1
kind: Service
metadata:
  name: web-ui
  namespace: test-app
  labels:
    app: web-ui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-ui
  type: LoadBalancer