apiVersion: v1
kind: Namespace
metadata:
  name: tanzu-system-logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit-extension-sa
  namespace: tanzu-system-logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fluent-bit-extension-role
  namespace: tanzu-system-logging
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fluent-bit-extension-rolebinding
  namespace: tanzu-system-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fluent-bit-extension-role
subjects:
- kind: ServiceAccount
  name: fluent-bit-extension-sa
  namespace: tanzu-system-logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-extension-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-extension-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-extension-cluster-role
subjects:
- kind: ServiceAccount
  name: fluent-bit-extension-sa
  namespace: tanzu-system-logging
---
apiVersion: v1
data:
  values.yaml: I0BkYXRhL3ZhbHVlcwojQG92ZXJsYXkvbWF0Y2gtY2hpbGQtZGVmYXVsdHMgbWlzc2luZ19vaz1UcnVlCi0tLQpsb2dnaW5nOgogIGltYWdlOgogICAgcmVwb3NpdG9yeTogcHJvamVjdHMucmVnaXN0cnkudm13YXJlLmNvbS90a2cKdGtnOgogIGluc3RhbmNlX25hbWU6ICJkZXYtY2x1c3RlciIKICBjbHVzdGVyX25hbWU6ICJkZXYtY2x1c3RlciIKZmx1ZW50X2JpdDoKICBvdXRwdXRfcGx1Z2luOiAiZWxhc3RpY3NlYXJjaCIKICBlbGFzdGljc2VhcmNoOgogICAgaG9zdDogImVsYXN0aWNzZWFyY2guc2hhcmVkLmgyby00LTEzODQuaDJvLnZtd2FyZS5jb20iCiAgICBwb3J0OiAiODAi
kind: Secret
metadata:
  name: fluent-bit-data-values
  namespace: tanzu-system-logging
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: fluent-bit
  namespace: tanzu-system-logging
  annotations:
    tmc.cloud.vmware.com/managed: "false"
spec:
  syncPeriod: 5m
  serviceAccountName: fluent-bit-extension-sa
  fetch:
    - image:
        url: projects.registry.vmware.com/tkg/tkg-extensions-templates:v1.3.1_vmware.1
  template:
    - ytt:
        paths:
          - tkg-extensions/common
          - tkg-extensions/logging/fluent-bit
        inline:
          pathsFrom:
            - secretRef:
                name: fluent-bit-data-values
  deploy:
    - kapp:
        rawOptions: ["--wait-timeout=5m"]
