---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: test-app-gateway
  namespace: test-app
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - '*'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtualservice-ingress-test-app
  namespace: test-app
spec:
  hosts:
  - test-app.apps.h2o-4-1384.h2o.vmware.com
  gateways:
  - test-app-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: test-nodejs-app
        port:
          number: 80
        subset: v1
      weight: 100
    - destination:
        host: test-nodejs-app
        port:
          number: 80
        subset: v2
      weight: 0
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: test-nodejs-app
  namespace: test-app
spec:
  host: test-nodejs-app
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
