apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cc-01
  namespace: tanzuns1
spec:
  topology:
    class: tanzukubernetescluster
    version: v1.23.8---vmware.2-tkg.2-zshippable
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
        - class: node-pool
          name: node-pool-1
          replicas: 1
    variables:
    - name: vmClass
      value: best-effort-small
    - name: storageClass
      value: "tanzu"
