apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  namespace: test-app
spec:
  selector:
    matchLabels:
      app: config-server
  replicas: 1
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: harbor.mgt.mytanzu.org/banking-demo/config-server:0.0.1-SNAPSHOT
        env:
        - name: WAVEFRONT_TOKEN
          value: change-me
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: test-app
  labels:
    app: config-server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: config-server
  type: ClusterIP