apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
  namespace: test-app
spec:
  selector:
    matchLabels:
      app: account-service
  replicas: 1
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: harbor.mgt.mytanzu.org/banking-demo/account-service:0.0.1-SNAPSHOT
        env:
        - name: spring.cloud.config.uri
          value: http://config-server.test-app.svc.cluster.local
        - name: WAVEFRONT_TOKEN
          value: change-me
        - name: spring.cloud.config.fail-fast
          value: "true"
        - name: spring.cloud.config.retry.max-interval
          value: "10000"
        - name: spring.cloud.config.retry.max-attempts
          value: "2000"
        - name: EUREKA_URL
          value: http://discovery-server.test-app.svc.cluster.local/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: test-app
  labels:
    app: account-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: account-service
  type: ClusterIP