apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui-v1-deployment
  namespace: test-app
spec:
  selector:
    matchLabels:
      app: web-ui
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: web-ui
        version: v1
    spec:
      containers:
      - name: web-ui
        image: harbor.mgt.mytanzu.org/banking-demo/web-ui:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        env:
        - name: spring.cloud.config.uri
          value: http://config-server.test-app.svc.cluster.local
        - name: WAVEFRONT_TOKEN
          value: change-me
        - name: spring.cloud.config.fail-fast
          value: "true"
        - name: spring.cloud.config.retry.max-interval
          value: "10000"
        - name: spring.cloud.config.retry.max-attempts
          value: "2000"
        - name: EUREKA_URL
          value: http://discovery-server.test-app.svc.cluster.local/eureka
        - name: DEP_NS
          value: test-app
        - name: customFrontendVar
          value: v1
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui
  namespace: test-app
  labels:
    app: web-ui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-ui
  type: ClusterIP