---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-console-tls
  namespace:  tanzu-helm-resource
spec:
  commonName: minio-console.mgt.mytanzu.org
  dnsNames:
  - minio-console.mgt.mytanzu.org
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  subject:
    organizations:
    - vmware
  renewBefore: 360h0m0s
  secretName: minio-console-tls
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: minio-console
  namespace: tanzu-helm-resource
spec:
  routes:
  - services:
    - name: minio-deploy
      port: 9001
  virtualhost:
    fqdn: minio-console.mgt.mytanzu.org
    tls:
      secretName: minio-console-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-api-tls
  namespace:  tanzu-helm-resource
spec:
  commonName: minio.mgt.mytanzu.org
  dnsNames:
  - minio.mgt.mytanzu.org
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  subject:
    organizations:
    - vmware
  renewBefore: 360h0m0s
  secretName: minio-api-tls
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: minio-api
  namespace: tanzu-helm-resource
spec:
  routes:
  - services:
    - name: minio-deploy
      port: 9000
  virtualhost:
    fqdn: minio.mgt.mytanzu.org
    tls:
      secretName: minio-api-tls
