apiVersion: v1
data:
  username: dXNlcm5hbWUtZnJvbS1zZWNyZXQK
  password: cGFzc3dvcmQtZnJvbS1zZWNyZXQK
kind: Secret
metadata:
  name: gorkem-secret
  namespace: test-app
type: Opaque
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app-sa
  namespace: test-app
secrets:
- name: gorkem-secret